### ISSUE TITLE
New file hashes for existing manifest entries generated from remote-file-manifests don't get updated in bags

### ISSUE THREAD

**Issue by eliasmarkc** [fair-research/bdbag#34]
When I try the examples in the CLI Guide and run:
```
bdbag ./test_bag/ --update --remote-file-manifest ./test-fetch-manifest.json
bdbag ./test_bag/ --resolve-fetch all
bdbag ./test_bag/ --validate full
```
The hash for at least the first example file isn't matching the downloaded file. The hashes in the documentation should be updated.

More importantly, I notice that when you provide the wrong or outdated SHA256 file hash in the remote file manifest and try to update the hash after, it doesn't update the hash in `manifest-sha256.txt`. It says to remove the data files associated with the mismatch. I do that, then try to update the hashes again with `--update --remote-file-manifest ./test-fetch-manifest.json`, and when I do a `--resolve-fetch all` followed by `--validate full`, the hash still hasn't updated and still fails to validate.

I tried adding a new file to the `test-fetch-manifest.json` and ran `--update --remote-file-manifest ./test-fetch-manifest.json` and noticed the new file was added as expected to the `manifest-sha256.txt` as well as `fetch.txt`.

My expectations as a user are that when you run an `--update --remote-file-manifest ./manifest.json`, the `manifest-*.txt` in the bdbag should be overwritten when noticing pre-existing files have new hashes.

**Comment by mikedarcy** [comment]
Fixed in release [1.5.6](https://github.com/fair-research/bdbag/releases/tag/v1.5.6).
