### ISSUE TITLE
conda-forge distribution?

### ISSUE THREAD

**Issue by sterlingbaldwin** [fair-research/bdbag#35]
It would be awesome to have this up on conda-forge so it can be used by other conda packages as a dependency. If you dont want to go through the trouble I dont mind setting it up (or maybe its already there and I didnt see it?).

**Comment by mikedarcy** [comment]
This is a reasonable request, but I would like to look into the particulars of what it would entail since I am not already familiar with conda-forge.

**Comment by sterlingbaldwin** [comment]
Its fairly straight forward, see the "Getting Started" section [here](https://github.com/conda-forge/staged-recipes).

**Comment by mikedarcy** [comment]
From what I can tell, the conda-forge folks never accepted this even though @sterlingbaldwin implemented everything required. Not sure why it went stale. We can always try again and either re-open this issue or create a new one.

**Comment by mikedarcy** [comment]
This eventually got done! Many thanks to @sterlingbaldwin for getting it started and @bernt-matthias for getting it over the finish line.
